### ISSUE TITLE
Module '"@oslojs/jwt"' has no exported member 'JWTRegisteredClaims'

### ISSUE THREAD

**Issue by tmrsiteops** [oslo-project/jwt#3]
I installed @oslojs/jwt via `npm i @oslojs/jwt` and the import statement in the documentation throws this error in my vite-based local environment (typescript).

`Module '"@oslojs/jwt"' has no exported member 'JWTRegisteredClaims'`

I searched around in the node module itself and the only occurence of JWTRegisteredClaims returned is in the README.md. Am I missing something?

**Comment by pilcrowonpaper** [comment]
Fixed with 0.3.0. Seems like I forgot to rename `JWTClaims`

**Comment by tmrsiteops** [comment]
Thank you!
